export enum InterviewDecisionType {

    FOLLOW_UP =
        "FOLLOW_UP",

    PROBE_CLAIM =
        "PROBE_CLAIM",

    CHANGE_ANGLE =
        "CHANGE_ANGLE",

    RECOVER_CONVERSATION =
        "RECOVER_CONVERSATION",

    CLARIFY_CONTRADICTION =
        "CLARIFY_CONTRADICTION",

    MOVE_TO_NEXT_CLAIM =
        "MOVE_TO_NEXT_CLAIM",

    MOVE_TO_NEXT_STAGE =
        "MOVE_TO_NEXT_STAGE",

    FINISH_INTERVIEW =
        "FINISH_INTERVIEW",
}