export enum ResumeClaimType {
    PROJECT = "PROJECT",

    WORK_EXPERIENCE = "WORK_EXPERIENCE",

    SKILL = "SKILL",

    CERTIFICATION = "CERTIFICATION",

    ACHIEVEMENT = "ACHIEVEMENT",

    OPEN_SOURCE = "OPEN_SOURCE",

    RESEARCH = "RESEARCH",

    PUBLICATION = "PUBLICATION",

    LEADERSHIP = "LEADERSHIP",

    EDUCATION = "EDUCATION",

    OTHER = "OTHER",
}